### ISSUE TITLE
Publish to maven/ivy repository

### ISSUE THREAD

**Issue by mavarazy** [keenlabs/KeenClient-Scala#18]

**Comment by gphat** [comment]
The snapshot is now available [at sonatype](https://oss.sonatype.org/content/repositories/snapshots/io/keen/keenclient-scala_2.11/0.4.0-SNAPSHOT/)!

**Comment by gphat** [comment]
Working on getting the non-snapshot shipped now.

**Comment by ches** [comment]
Woot! Might want to publish the cross version for 2.10 too, either `+ publishSigned` or `++ 2.10.4 publishSigned`, etc.

Happy New Year! :tada:

**Comment by gphat** [comment]
I did when publishing the real version. Working on some POM failures and such right now.

**Comment by gphat** [comment]
Waiting around for my key to reliably appear on the keyservers. :)

**Comment by gphat** [comment]
[Done](http://search.maven.org/#search%7Cga%7C1%7Ckeenclient-scala).
