### ISSUE TITLE
ScalaTest?

### ISSUE THREAD

**Issue by ches** [keenlabs/KeenClient-Scala#43]
Just raising a question here since I know Keen uses some Scala internally… do you tend to use Specs2 or ScalaTest?

Totally a matter of subjective preference, but I always find specs2 kind of cumbersome, feels like friction every time I need to figure out how to do something a little beyond the basics, and then once I do I often find the APIs aesthetically distasteful :innocent:  There's surely bias of familiarity at play, granted.

If maintainers have any interest in switching this project to ScalaTest, I'm willing to help port the suite. If you're happier with Specs2 then just disregard this, I'll live with it :smile:

**Comment by terryhorner** [comment]
We use Specs2 :confused:.

**Comment by ches** [comment]
Drat. No worries, thanks for the answer!
